import type { Metadata } from "next";
import "../styles/global.css";
import ResponsiveLayout from "@/components/ConditionalSidebar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="antialiased bg-background">
        <ResponsiveLayout>{children}</ResponsiveLayout>
      </body>
    </html>
  );
}
